#cloud-config
cloud_final_modules:
- [users-groups,always]
users:
  - name: ubuntu
    groups: [ sudo ]
    sudo: [ "ALL=(ALL) NOPASSWD:ALL" ]
    shell: /bin/bash
    ssh-authorized-keys:
    - ${ssh_public_key}